AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda that fetches API data and stores in S3

Resources:

  ApiDataBucket:
    Type: AWS::S3::Bucket

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: "*"
              - Effect: Allow
                Action:
                  - logs:*
                Resource: "*"

  ApiLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: lambda.app.lambda_handler   #  fixed
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: my-cf-api-lambda-s3      #  consistent name
        S3Key: lambda.zip
      Environment:
        Variables:
          BUCKET_NAME: !Ref ApiDataBucket #  fixed