name: Deploy Lambda CloudFormation

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Zip Lambda Function
        run: zip -r lambda.zip lambda

      - name: Upload Lambda Zip to S3
        run: |
          aws s3 mb s3://my-cf-api-lambda-s3 --region ${{ secrets.AWS_REGION }} || true
          aws s3 cp lambda.zip s3://my-cf-api-lambda-s3/lambda.zip

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file lambda/template-lambda.yml \
            --stack-name api-lambda-stack-lambda-s3-1 \
            --capabilities CAPABILITY_NAMED_IAM
            --no-fail-on-empty-changeset

      - name: Describe Stack Events on Failure
        if: failure()
        run: |
          aws cloudformation describe-stack-events \
            --stack-name api-lambda-stack-lambda-s3 \
            --query 'StackEvents[?ResourceStatus==`CREATE_FAILED` || ResourceStatus==`UPDATE_FAILED`].[ResourceType,ResourceStatusReason]' \
            --output table